url: "http://www.daniellegrau.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "https://dgrau13.github.io/" # the subpath of your site, e.g. /blog
title: "Danielle K. Grau Ph.D." # the name of your site, e.g. ACME Corp.
description: "PhD in Earth & Atmospheric Sciences"
