menu:
- {name: 'research', url: '/research'}
- {name: 'publications', url: '/publications'}
- {name: 'cv', url: '/assets/cv/DGrauCV_250808.pdf'}
- {name: 'contact', url: '/contact'}

research:
- {name: 'Self-Affinity of the Antarctic Ice Sheet', image: 'assets/img/Project1.png'}
- {name: 'Physics-Based Parameterizations for Mean Supraglacial Melt Lake Depth and Area Fraction', image: 'assets/img/CroppedCWalker.gif'}
- {name: 'Implementation of Supraglacial Melt Lake Parameterizations into ISSM Calving Scheme', title: 'SGLs into ISMIP6', image: 'assets/img/graduate-student.jpg'}

social:
- {icon: 'github', link: 'https://github.com/dgrau13'}
- {icon: 'bluesky', link: 'https://bsky.app/profile/dgrau13.bsky.social'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/danielle-grau'}

contacts:
- {name: 'Danielle Grau', title: 'Graduate Research Assistant', department: 'Earth and Atmospheric Sciences', institution: 'Georgia Institute of Technology', institution_address: '311 Ferst Dr., Atlanta, Georgia 30318, USA', email: 'dgrau7@gatech.edu', office: 'ES&T 2124', image: 'assets/img/contact.JPG'}
